version: '3'

services:
  frontend:
    image: guyuan404643/markitdown-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8008

  backend:
    image: guyuan404643/markitdown-backend:latest
    ports:
      - "8008:8008"
    environment:
      - EXIFTOOL_PATH=/usr/bin/exiftool
